services:
    miguel_alcaino.iugu_service:
        class: MiguelAlcaino\IuguBundle\Services\PaymentService
        arguments:
            - "%iugu.token%"
            - "%currency%"
            - "%business_name%"
            - "%is_paid_in_cents%"
            -  "%refunded_status%"
